### ISSUE TITLE
CPU and GPU cores not at 100%

### ISSUE THREAD

**Issue by CarrotCultivator** [beyond-all-reason/spring#1007]
Hello to the team.
I do not have much internal information about the cause of this, but while running the BAR benchmark (say, with Tanks), the GPU is not at 100% and no CPU thread is at 100%. I believe something is bottlenecking the CPU as lowering the resolution does not increase performance.
In other words, I believe there is performance left on the table (perhaps +10-20%) judging by the maximum CPU utilization.
I tried to do a (very) simple profiling but I was lost in the internals. Initially I thought that the worker loop at https://github.com/beyond-all-reason/spring/blob/BAR105/rts/System/Threading/ThreadPool.cpp#L209 is waiting too long (30 ms) to poll, but changing this value did not make the benchmark faster.
I also noticed that there are many calls to luaD_seterrorobj() at https://github.com/beyond-all-reason/spring/blob/BAR105/rts/lib/lua/src/ldo.cpp#L51 , perhaps that may cause slowdowns.

In any case, when I find more time I will try to investigate further, but my knowledge of the Spring internals is very limited. Perhaps you guys have an idea of what may be holding back the CPU, it would be nice if a simple fix allowed some more hundreds of units :P

Edit: In order to obtain the full BAR performance while looking at a separate window (like the task manager), there is an option that needs to be deactivated in the Settings. I have disabled it, the issue still persists.

**Comment by lhog** [comment]
Besides fixing bugs and adding new features the rest of the engine devs' time goes into exploring ways to improve the engine performance. The performance metrics will never reach 100% because we don't do one simple task like mining bitcoins, but rather execute a very complex graph of actions. Expecting 100% load on both CPU and GPU sides is not realistic.

What is helpful and you're on the right track there is to identify specific bottlenecks and challenge us to have a look and improve. Many such bottlenecks cannot be improved immediately or just a toll we need to pay for using certain technologies, like Lua error reporting you mentioned. This should not discourage you though as once in a while we indeed find ways to improve.

I'm closing this one as it's not specific enough, but feel free to open up specific requests for investigation. We recently integrated Tracy profiler in the engine, but for performance reasons it's not enabled in the public engine releases. We would like to get perf reports along with Tracy traces, but in order to generate them you will have to download specific builds and generally learn how to use Tracy and other tools. Hit us up on Discord's `#engine` so we can discuss.
