### ISSUE TITLE
Sanitize unitDef.corpse

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1024]
`UnitDefs[x].corpse` should be "" or nil if the input string does not refer to a valid feature def name. Currently it regurgitates the invalid name from the def input.

**Comment by A-Lias** [comment]
Hey @sprunk -- I was the one who pushed the PR for this yesterday. I'm new to the codebase and want to make sure I understand what's going on, can you help a little?

Above you reference setting UnitDefs[x].corpse = "" or nil, which is a thing in Lua, but obviously isn't quite the same inside the engine. In the engine's unitDefHandler there is a unitDefsVector, but a UnitDef does not have a corpse field, only a wreckName field. That's why my first thought was that you wanted a quick fix inside the Lua featuredefs parsing.

It seems your overall goal is to have LuaUnitDefs create the UnitDefs table with sanitized corpse entries. That means each unitDef created in the engine needs to have the corpse/wreckName validated against all featureDefs and, if no matching featureDef is found, for the corpse/wreckName to be modified to "". Is that right?

If that's the goal, I believe the latest commit on the PR solves that. Will you check? Right after unitDefHandler and featureDefHandler are initialized inside CGame::PostLoadSimulation, a call to unitDefHandler.SanitizeCorpseNames checks each UnitDef and sanitizes unitDef.wreckName = "" for any wreckNames that are not associated with a featureDef. I think this should mean that, down the line, LuaUnitDefs creates the UnitDefs table correctly.

I couldn't do the sanitization inside the unitDefHandler initialization because featureDefHandler isn't initialized until after unitDefHandler, and I thought changing the initialization order would probably cause problems.

Alternatively, I think this could all be performed within LuaUnitDefs. But it would involve modifying unitDefHandler to return non-const unitDefs.

I briefly play tested the most recent commit and it didn't seem to cause problems. But I'm also not sure what you meant about non-builtin corpses. Can you explain what that means and if that's an issue for this approach also?

**Comment by sprunk** [comment]
Looks good! I'll test but I expect it to be correct.

> It seems your overall goal is to have LuaUnitDefs create the UnitDefs table with sanitized corpse entries

Exactly.

> I'm also not sure what you meant about non-builtin corpses.

It means corpses which aren't defined in the same unit's featureDefs table. For example because they are defined in another unit, or are a standalone feature (like a tree or something). Here's an example:
```lua
-- a.lua
corpse = "dead", -- Lua post-processing turns it into "a_dead"
featureDefs = {
  dead = { ... }
}
```
```lua
-- b.lua
corpse = "a_dead", -- your earlier patch would make it try "b_a_dead", see it missing, and turn it into "". But leaving it as "a_dead" is actually fine, it's just inside unit A.
featureDefs = { -- the post-processing logic only applies if this table exists, but there are good reasons not to delete (eg. quick iteration)
  dead = { ... }
}
```
```lua
-- c.lua
corpse = "tree", -- your earlier patch would make it try "c_tree", see it missing, and turn it into "". But leaving it as "tree" is actually fine, maybe it's defined as a standalone feature.
featureDefs = {}
```

**Comment by A-Lias** [comment]
Got it, thanks for the explanation. Hopefully future contributions will come a bit more easily now :)
