### ISSUE TITLE
High cost of QTPFS pathfinding search in some cases (2152) 

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#1137]
Scenario: Red River Remake v1.2 map, pathfinding request 100 armpw units to another coast.
https://youtu.be/bV_AKDUeXnw

**Comment by marcushutchings** [comment]
Are reference, the units are unable to cross the river, and so the pathing system has to find the cloest point, which would mean the pathing system has to search the whole of the island on the left. We have early-out detection for similar scenarios, which that requires the reverse search to exhaust its search space. In this case, the island on the right is a similar huge size as on the left, which means even if the reverse search runs out of search quads first, the search system will have gone through a lot of quads. I'm open to those with experience in programming pathing systems to offer ideas on how we can improve the performance here.

Island tagging isn't ideal because the game is dynamic and can join islands, or make make new islands (in a pathing sense) during a match - and we can't cost-effectively recalculate island tags in realtime. Unless, perhaps, we do island tagging during load and throw away tags once invalid and never generate them again during a match? In this map's case, it is highly unlikely that the two islands will be joined.

**Comment by marcushutchings** [comment]
More updates have gone into the mainline. How are the performance issues looking?

**Comment by 6AKU66** [comment]
> More updates have gone into the mainline. How are the performance issues looking?

Performance now is ok with (~8000 quads seacrhed). But need to resolve red square pathfinding issue.

**Comment by marcushutchings** [comment]
The specific issue raised originally has been resolved. Closing this ticket.
