### ISSUE TITLE
InBuildStance fix

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#128]
Currently builders can start building before finishing their build stance animation, so I had to make a workaround with a synced script to make them work properly, unpacking and rotating turrets and then starting building.
Take a look at this line of code:
https://github.com/beyond-all-reason/spring/blob/057e4bbec9aa9d8bcfc36dea0343ef88c1a3c2e5/rts/Sim/Units/UnitTypes/Builder.cpp#L329

The reasoning behind this (written above the code) is probably understandable.
I propose to add a function like SetBuildStanceRequiredToBuild that would affect all builders globally, so developers may choose to use it or not.
Then the condition should change like
if (!(inBuildStance || true)) --> if (!inBuildStance && IsBuildStanceRequiredToBuild)

**Comment by Krogoth100** [comment]
Maybe solution is not that simple and that line of code won't fix the issue, I will take a deeper look later.
I will rephrase the problem: "Builders start repairing regardless if INBUILDSTANCE flag is set to 0" - need a way to make builders respect INBUILDSTANCE flag.

**Comment by lhog** [comment]
Also bear in mind, I haven't written these LoCs nor read them thoroughly.
I cannot provide an expert opinion outside of the things I'm proficient with, so if you happen to find some some solution, better do a PR yourself, otherwise issues like this one will need to wait the moment I'm well acquainted with that particular part of the code.
