### ISSUE TITLE
Decals questions / postmortem review

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1314]
Partially questions for documentation, partially feedback.

1. `Spring.GetDecalType` no longer returns "building" but can now return "plate". What's the difference, isn't this just the building plate?
2. `Spring.GetDecalAlpha` returns falloff as the 2nd arg but Set doesn't allow you to set it.
3. what textures are returned by `Spring.GetDecalTextures`? Currently used? Currently cached (= used at least once, possibly currently expired)? All known to be possible decals (= currently cached + known to be defined as tracks/plates for units/buildings that haven't yet been made)? Other?
4. `Get/SetDecalTexture(s)` has a new boolean `isMainTex` param. I assume the "not main" tex is the normal. If so then it's not obvious (also what if more "meta" textures are added?), perhaps consider changing the interface `isMain (default true)` to `isNormal (default false)`.
5. `Get/SetDecalCreationFrame` has two frames, min and max. Surely it only takes one frame to create a decal? It seems to be used for tracks somehow, is the track no longer a collection of single-section decals each with a single-frame creation time? Needs better names or a description.
6. on the normal map, is 255 alpha (fully opaque) the "glowing hot" or the "cold" part? Perhaps it should be cold since that will cover most of the texture. This is a common complaint with regular unit textures: teamcolor is fully opaque meaning you can only see black blobs under the teamcolor while the actual colored part of the texture is transparent and not easily visible.
7. can I control the glow's behaviour other than via the normal texture's alpha channel, or do I have to replace the shader code?
8. does the file extension of the normal tex have to match the main tex? E.g. if i have `x.TGA` does it have to be `x_normal.TGA` or can it be `x_normal.DDS` or `x_normal.PNG` etc?
9. `SetDecalQuadPosAndHeight`, `SetDecalPosAndDims` and the relevant getters seem to assume there's only X and Z coordinates. Can't I control the Y coordinate? Decals not conforming to the ground could be useful. For example you might want this sort of leaf as a decal on the water surface (and not on the "ground" i.e. underwater):
![image](https://github.com/beyond-all-reason/spring/assets/2573076/30670449-e7e8-467a-a640-9485152df289)
Or idk, spider web decal between a tree and a nearby cliff.

**Comment by lhog** [comment]
> Spring.GetDecalType no longer returns "building" but can now return "plate". What's the difference, isn't this just the building plate?

This has never worked, as the whole decal API was guarded by `if decalsGL4` clause, and decalsGL4 was never enabled/finished.
As for the return. It's just a choice of words (the area, where I have always been below average). Basically a texture below a building or ghost of the building.

> Spring.GetDecalAlpha returns falloff as the 2nd arg but Set doesn't allow you to set it.

Probably an oversight, should be fixable. I'll be fixing the implementation crash this weekend, will have a look at this one and also on the comment you left under the code (I think you spotted a 100% bug there).

> what textures are returned by Spring.GetDecalTextures? Currently used? Currently cached (= used at least once, possibly currently expired)? All known to be possible decals (= currently cached + known to be defined as tracks/plates for units/buildings that haven't yet been made)? Other?

It will return the internal name of sub-textures in the atlas. For now the atlas is built once upon the game load. It was tempting to give the game devs an ability to load their own textures through the API, but unfortunately the fact it has deal with atlas of textures makes the process quite fragile. I considered adding something like that later.

> Get/SetDecalTexture(s) has a new boolean isMainTex param. I assume the "not main" tex is the normal. If so then it's not obvious (also what if more "meta" textures are added?), perhaps consider changing the interface isMain (default true) to isNormal (default false).

Yes, the implementation works with two textures (main - diffuse/alpha and normal - normal/glow ones). Maybe The function should return the atlas number indeed.

> on the normal map, is 255 alpha (fully opaque) the "glowing hot" or the "cold" part? Perhaps it should be cold since that will cover most of the texture. This is a common complaint with regular unit textures: teamcolor is fully opaque meaning you can only see black blobs under the teamcolor while the actual colored part of the texture is transparent and not easily visible.

`255/1.0f` indicates parts that should glow the hottest. What you suggest makes sense for an untrained artist, but generally quite counterintuitive, it also contradicts conventions established in commercial texture samples I have seen. Idk about that one.

> can I control the glow's behaviour other than via the normal texture's alpha channel, or do I have to replace the shader code?

The amount of damage controls it indirectly (no or little glow for tiny damage amounts). Overall it can be added I suppose. The only question is how. My go to move has been to expose it via API in a most direct way, but for explosions that doesn't sound like a good idea (and it's probably doable with the existing API already). So something to think about.

> does the file extension of the normal tex have to match the main tex? E.g. if i have x.TGA does it have to be x_normal.TGA or can it be x_normal.DDS or x_normal.PNG etc?

IIRC yes. Otherwise it makes it unclear what should I load if both are available: x_normal.DDS or x_normal.PNG?

> SetDecalQuadPosAndHeight, SetDecalPosAndDims and the relevant getters seem to assume there's only X and Z coordinates. Can't I control the Y coordinate? Decals not conforming to the ground could be useful. For example you might want this sort of leaf as a decal on the water surface (and not on the "ground" i.e. underwater):

The implementation can only project onto the ground, hence the name of the class. Generally it should project on something that is "not moving", though it should tolerate moderate terrformation just fine.
Projecting onto the water plane or e.g. units will require two different techniques (and separate implementation unfortunately).

**Comment by sprunk** [comment]
> For now the atlas is built once upon the game load. It was tempting to give the game devs an ability to load their own textures through the API, but unfortunately the fact it has deal with atlas of textures makes the process quite fragile. I considered adding something like that later.

Does that mean the code below would only work if the texture happens to already be on the atlas for other reasons (like being listed as an explosion/plate/track decal on some unit)?
```lua
local decal = Spring.CreateDecal()
Spring.SetDecalTexture(decal, "some/random/texture.dds")
```

>  it also contradicts conventions established in commercial texture samples I have seen

Sure, better to stick to industry standards.

> The amount of damage controls it indirectly (no or little glow for tiny damage amounts).

Could it be a new weapon trait which defaults to damage (instead of using damage directly)? I think ZK would like the new decals for "normal" weapons but I wouldn't want it on weapons that have large "damage" but actually convert it to something else in a gadget (like capture or slow).

> can only project onto the ground, hence the name of the class.

The names of all the Lua interfaces say just "decal" though, which is what game devs will see (and not the C++ class names). Perhaps they should be GroundDecal everywhere in case there's also arbitrary non-ground decals in the future, and for self-documentation?

**Comment by lhog** [comment]
Yeah it's impossible to inject new textures by the file name for now. It might generally be doable. I'll add something when there's a demand.

As for the new weapon tag, yeah maybe that's the way. I slightly dislike this way, but it's the most performant one, yes.

I'll probably change Decal --> GroundDecal in the Lua API.
