### ISSUE TITLE
EngineCrash [1.1340.0] at [4294966293]

### ISSUE THREAD

**Issue by IkkeTM** [beyond-all-reason/spring#1435]
**URL of infolog.txt**
[infolog.txt](https://github.com/beyond-all-reason/spring/files/14962569/infolog.txt)

**Engine Version**
105.1.1-1354-g72b2d55 bar

**Translated Stack Trace with links**

```
Translated goes here, with links!

```

**Additional context**
What the stack trace asks of me I have little idea, but when I start the program it tells me: 
error generating map: texture generation not supported

Someone on discord adviced me to post the issue here, so I hope this helps.

If there is anything else I can provide I'd be happy to.

**Comment by lhog** [comment]
Please set `DebugGL=1` in springsettings.cfg and then do the same thing you do and provide new infolog.
Generally the reported 1354 engine is quite ancient (same applies to the actual engine you're using - 105.1.1-1775-g441af87).

**Comment by IkkeTM** [comment]
Alright, here's the new log.
[infolog.txt](https://github.com/beyond-all-reason/spring/files/14963303/infolog.txt)

I thought I downloaded the latest version of springboard from  https://github.com/Spring-SpringBoard/SpringBoard-Core?tab=readme-ov-file
I also don't know what do with the files in the link you provided, I download them, extract them, and then what?
When I tell springboard to download the development version of BAR the download fails (possibly also visible in the log)

**Comment by IkkeTM** [comment]
Get the same error there too. :/
[infolog.txt](https://github.com/beyond-all-reason/spring/files/14963452/infolog.txt)

**Comment by IkkeTM** [comment]
[infolog.txt](https://github.com/beyond-all-reason/spring/files/14963476/infolog.txt)
There it is, forgot about setting that.

**Comment by lhog** [comment]
One of you please find me in BAR or Recoil Discord, I'm going to send you a binary with a fix attempt.

**Comment by IkkeTM** [comment]
Another log, now with the exe you provided.
[infolog.txt](https://github.com/beyond-all-reason/spring/files/14963618/infolog.txt)
 Launching the .exe seperatily works.

**Comment by Universal-Invariant** [comment]
This has nothing to do with versions. BAR did not update and it crashed. There is a bug in the save and loading. Sometimes my units won't do squat when loaded or who do certain actions. Sometimes whatever they were doing during the save will not carry over and they will be stuck. Sometimes they will be stuck in a single animation frame and just hover around doing nothing. They won't attack. Other times it is just a single function that refuses to work  such as trying to repair. Essentially the save/load feature is unusable because it always glitches out. I have noticed the issue once in a multiplayer game where my con was not building but just sitting there. This has nothing to do with lack of resources. There are various glitches with text that seem to happen too along with strange glitches in buildings being rendered in different locations and audio such as the new voice saying ammander rather than commander. I put the graphics on lowest which doesn't help except of course with the fps. Usually I get about 180fps in multiplayer games. If a game is started from scratch there usually are no issues. Only when loading does everything go to hell. I believe it likely has to do with the Intel Arc graphics card. There must be some incompatibility that is causing a bug as it seems no one else experiences these types of problems as I can't find issues about it.

[infolog.txt](https://github.com/user-attachments/files/23692904/infolog.txt)


[t=00:00:12.241807][f=-000001] [featuredefs_post.lua] Warning: Removing feature def, corhack_dead, for having invalid model that would crash the engine, Units/corfast_dead.s3o
[t=00:00:12.241889][f=-000001] [featuredefs_post.lua] Warning: Removing feature def, xmascomwreck, for having invalid model that would crash the engine, gingerbread
[t=00:00:12.242195][f=-000001] [featuredefs_post.lua] Warning: Removing feature def, corfast_dead, for having invalid model that would crash the engine, Units/corfast_dead.s3o
[t=00:00:12.250778][f=-000001] [~ScopedOnceTimer][Loading all definitions: ] 91ms
[t=00:00:12.264573][f=-000001] [~ScopedOnceTimer][Game::LoadDefs (GameData)] 122ms
[t=00:00:12.266343][f=-000001] [LoadScreen::SetLoadMessage] text="Loading Radar Icons"
[t=00:00:12.266754][f=-000001] Warning: [OPENGL_DEBUG] id=13 source=API type=DEPRECATED severity=MEDIUM msg="API_ID_DEPRECATED_TARGET deprecated behavior warning has been generated. Enable of GL_LIGHTING capability is deprecated."
[t=00:00:12.267435][f=-000001] Warning: [OPENGL_DEBUG] id=8 source=API type=PERFORMANCE severity=LOW msg="API_ID_REDUNDANT_FBO performance warning has been generated. Redundant state change in glBindFramebuffer API call, FBO 0, "", already bound."
[t=00:00:12.533922][f=-000001] Warning: [CIconHandler::Update] Failed to load icon=default_scav, bitmap=
[t=00:00:12.640444][f=-000001] Warning: [CIconHandler::Update] Failed to load icon=default, bitmap=
[t=00:00:12.757949][f=-000001] Warning: [OPENGL_DEBUG] id=8 source=API type=PERFORMANCE severity=LOW msg="API_ID_REDUNDANT_FBO performance warning has been generated. Redundant state change in glBindFramebuffer API call, FBO 0, "", already bound."


The info file has about 5k lines of

```
[t=00:00:05.480719][f=-000001] Warning: [OPENGL_DEBUG] id=8 source=API type=PERFORMANCE severity=LOW msg="API_ID_REDUNDANT_FBO performance warning has been generated. Redundant state change in glBindFramebuffer API call, FBO 0, "", already bound."
[t=00:00:05.480957][f=-000001] Warning: [OPENGL_DEBUG] id=13 source=API type=DEPRECATED severity=MEDIUM msg="API_ID_DEPRECATED_TARGET deprecated behavior warning has been generated. Enable of GL_LIGHTING capability is deprecated."
[t=00:00:05.480987][f=-000001] Warning: [OPENGL_DEBUG] id=13 source=API type=DEPRECATED severity=MEDIUM msg="API_ID_DEPRECATED_TARGET deprecated behavior warning has been generated. Enable of GL_LIGHTING capability is deprecated."
[t=00:00:05.480997][f=-000001] Warning: [OPENGL_DEBUG] id=13 source=API type=DEPRECATED severity=MEDIUM msg="API_ID_DEPRECATED_TARGET deprecated behavior warning has been generated. Enable of GL_LIGHTING capability is deprecated."
````

I'm pretty sure that there was zero update when I played an saved the game and when I loaded it which was about a span of 10 minutes.

```
[t=00:00:16.808354][f=-000001] [LoadScreen::SetLoadMessage] text="Loading Saved Game"
[t=00:00:16.808448][f=-000001] Warning: [OPENGL_DEBUG] id=13 source=API type=DEPRECATED severity=MEDIUM msg="API_ID_DEPRECATED_TARGET deprecated behavior warning has been generated. Enable of GL_LIGHTING capability is deprecated."
[t=00:00:16.808682][f=-000001] Warning: [OPENGL_DEBUG] id=8 source=API type=PERFORMANCE severity=LOW msg="API_ID_REDUNDANT_FBO performance warning has been generated. Redundant state change in glBindFramebuffer API call, FBO 0, "", already bound."
[t=00:00:16.915178][f=-000001] Error: [Game::Load][7] forced quit with exception "Metadata checksum error: Package file was saved with a different version"
[t=00:00:16.915225][f=-000001] [WatchDog::DeregisterThread] deregistering controls for thread [main]
[t=00:00:18.876554][f=-000001] Fatal: [ExitSpringProcess] errorMsg="Errors:
Metadata checksum error: Package file was saved with a different version" msgCaption="Recoil: caught content_error(s)" mainThread=1
```

**Comment by lhog** [comment]
You mix up too many things in one comment and none of them is related to the original ticket.

**Comment by lhog** [comment]
I deleted your comment, don't be rude. Last warning before ban.

Your comment was unrelated to this issue, the save/load issue is being investigated in other place, the GL debug issue is also unrelated.

**Comment by Universal-Invariant** [comment]
> I deleted your comment, don't be rude. Last warning before ban.
> 
> Your comment was unrelated to this issue, the save/load issue is being investigated in other place, the GL debug issue is also unrelated.

Just ban me. I deleted the game. It will just make it much less likely I will ever install it. You seem to think because you say things it makes it true. If the issue is unrelated you should at least spend time fixing the error codes and messages rather than blaming the user. Ban me and delete the comment. This way I don't fall back into the asshole region of github. You say I'm rude while saying my comment on an issue in which I got the same error message and code is unrelated without any real investigation and any way to know if it was actually related or not. If I would have created a new issue you have claimed that the issue already exists and closed out that issue. The fact is you just get off on shutting people down and don't want to do any real work.

Again, I deleted the game. It is clear to me you guys are not serious about fixing bugs unless they effect you or someone does most of the work. So make yourself hard and ban me and delete the commend. You'll never be able to delete the facts I have outlined.

BTW, I blocked you and put "asshole" in the note. I suggest you do the same and go about your business of shutting people down rather than actually spending time fixing issues.

**Comment by B0rner** [comment]
@lhog 

> , the save/load issue is being investigated in other place

Could you please provide the issue-number for the load/save-problem?
I have troube loading a saved game. That works sometimes, somtimes not. Clicking the "load" button next to a saved game, the game is loading until the progress-bar reach something like 60%
After "[pathManager::InitNodeLayersThreaded] using 4 threads for 42...." the loading process crashed at "Loading saved games"
With an alert box containing "Errors: Metadata checksum error: Package file was saved with a differen version"

The game cloesed the screen and I see the launcher again with the Message: `"Spring failed with code: 4294966293"`

The code is the same like the one in the issue ther. This is becaus everyone who google for 4294966293 found this issue, which does not fit to the initial post.

**Comment by lhog** [comment]
https://github.com/beyond-all-reason/RecoilEngine/issues/2654

**Comment by lhog** [comment]
4294966293 is a generic crash code. Due to the unexplored nature of every crash it cannot be made more specific.

**Comment by B0rner** [comment]
> #2654

This one is about problems while saving the game. Saving the game works for me. My problem is, that I'm unable to load a saved game. If I load a game, I get the "Error: Metadata checksum error: Package file was saved with a different version."

But this is not true. Saved game version and game version are both the same.
Do you think this is the same topic like #2654?

**Comment by lhog** [comment]
I think so, but do post the savegame in that ticket.
