### ISSUE TITLE
Review & Merge libunitsync folder detection

### ISSUE THREAD

**Issue by PicassoCT** [beyond-all-reason/spring#150]
https://github.com/spring/spring/pull/568

**Comment by lhog** [comment]
I'm not entirely sure what the point of system wide installation is?
Is it done to run all games on a single engine version be it 105 or 106 or w/e? If so - this will never work for us as we switch engines once a week or so.

**Comment by mfld-fr** [comment]
Hello, I am the mentioned PR submitter on the original engine. Could you please close this issue, as I requested that PR on Spring and not on BAR ? It was a nice intent from @PicassoCT to help my PR to get merged on the original engine, but I think this issue is irrelevant here.

About the submitted patch itself, it is not related to any system wide installation as CMake caller can specify the actual destination folder with `CMAKE_INSTALL_PREFIX` or `DESTDIR`. Neither related to any folder detection.

**Comment by lhog** [comment]
Yep I'm not sure how it might improve the distribution method we chose.
