### ISSUE TITLE
Make original heightmap mutable. Take care of save/load and heightmap checksums

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#157]
See https://github.com/beyond-all-reason/Beyond-All-Reason/issues/671

There needs to be some callin to update the height towards which the restore command shifts ground.

**Comment by lhog** [comment]
Yep good idea.

**Comment by lhog** [comment]
Except then it needs to be saved/loaded too...

**Comment by sprunk** [comment]
Since the main use case is for making whole-map offsets, maybe `Spring.SetGlobalMapHeightOffset(h)`? Then you only need to save 1 value.

**Comment by marcushutchings** [comment]
I have a possible fix for this and one that's intended to be compatible with random maps as well (because they would be susceptable to the same issue in theory.) Essentially, call a new ReadMap::Finalize() function that will trigger ReadMap::InitHeightBounds() after Lua initialization (I believe InitHeightBounds should remain private for now - wrapping it allows for other implementation details to be brought into Finalize if it is needed and also to communicate the intent of the function in this particular purpose) - effectively calling from where ReadMap::UpdateHeightBounds() was put in CGame::Load().

ReadMap::InitHeightBounds() also regenerates the readmap map checksum, but I can't see where this map checksum gets used - in my searches so far I've only seen the map checksum from GameData get used, which is something else entirely as far as I can see. The change works on a simple test, but I'm wondering whether there is something else that needs to be done or checked to ensure it will work in multi-player games. We will obviously test it anyway, but if there are any further insights that may help head off any potential issues before testing that would be good.

**Comment by marcushutchings** [comment]
As for save/load. If the map starting point is changed from the map file, then we have to record this somehow. Maybe as a set of offsets like how map deformation is saved so to compress better (so setting map_waterlevel to 200 would yeald a long set of (-200) offsets.)

**Comment by marcushutchings** [comment]
Fixed submitted in PR: https://github.com/beyond-all-reason/spring/pull/281
