### ISSUE TITLE
Crash reports (798)

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#181]
https://github.com/ZeroK-RTS/CrashReports/issues/52304

https://github.com/ZeroK-RTS/CrashReports/issues/52327

**Comment by GoogleFrog** [comment]
3) Probably duplicates of (2) https://github.com/ZeroK-RTS/CrashReports/issues/52328 https://github.com/ZeroK-RTS/CrashReports/issues/52330

**Comment by lhog** [comment]
All the same issue. Non-GL4 system trying to init GL4 constructs, probably fixed in https://github.com/beyond-all-reason/spring/commit/a8c646a7a66fb7f8cc9d3d0ac624cc3684f8d1ab

Though `GeForce GTX 660/PCIe/SSE2` guy can probably upgrade his drivers: https://opengl.gpuinfo.org/
I wonder if this can be told by the launcher/engine somehow.

**Comment by lhog** [comment]
Coded https://github.com/beyond-all-reason/spring/commit/89aad9e291ff2410c07081a026a7c3cfd35ab393 but disabled for now since we are in bugfixing phase.

![image](https://user-images.githubusercontent.com/1476261/150656236-28c275ee-6dce-4125-871c-c46033c35189.png)
