### ISSUE TITLE
Some players report windows taskbar appearing in front of borderless window

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#183]
[infolog(12).txt](https://github.com/beyond-all-reason/spring/files/7918442/infolog.12.txt)

**Comment by lhog** [comment]
I see the guy plays at `1920,1040` resolution, with `0,0` window offset on `1920x1080` screen.
Looks like it should leave 40 px on the bottom for taskbar.

Can he provide full screen screenshot?

**Comment by GoogleFrog** [comment]
Spring.GetScreenGeometry() returns 1920, 1040 on my 1020x1080 monitor. These are the values fed to XResolutionWindowed and YResolutionWindowed when setting windowed borderless.

**Comment by lhog** [comment]
Ok I have refreshed my memory on the subject. Here it works:

* Manual window positioning during the game run is unconstrained. User can move and resize decorated window as much as they like, except resolution can't go below 400 for each dimension.
* On start and on programmatic change (by changing window related config variables via `Spring.SetConfigInt()` or main menu widget) the implementation does certain weak sanitation. In particular maximum bounds for all available displays are calculated. Then spring window is clamped to fit into these bounds. This is done to prevent cases of misconfiguration, accidential movement of window outside of display area, display configuration changes, etc.
* Next on our topic. I considered 4 fundamental modes:
   1. Fullscreen exclusive (aka fullscreen decorated) - occupies full screen of one display `Spring.GetScreenGeometry()` returns physically available size in pixels. This mode actively refuses attempts to alt-tab it.
   2. Fullscreen non-exclusive (aka fullscreen borderless) - occupies full screen of one display `Spring.GetScreenGeometry()` returns physically available size in pixels. This mode actively refuses attempts to alt-tab it.
   3. Windowed decorated - acts like your browser window, i.e. it stays within usable area of display, i.e. doesn't cover tray area and perhaps some other OS specific areas. Feels like regular window. `Spring.GetScreenGeometry()` returns **4** parameters (`sizeX, sizeY, posX, posY`) which should all be taken into account, because some people have tray on the left side and some on top, perhaps on the right side as well. This is rationale why `Spring.GetScreenGeometry()` return reduced area. This mode also yields non-nil 4 extra parameters (4th till 8th, counting from 1) of `Spring.GetWindowGeometry()`. These params represent window borders.
   4. Windowed Borderless - `Spring.GetScreenGeometry()` behavior is same. Window cannot be moved or resized with mouse, still movable/resizeable with springsettings/API.

I'm not sure the behavior above doesn't make sense. To me at least it does. Happy to hear objections,

But I can understand the need to have physical size in `Spring.GetScreenGeometry()` so I'm adding default on switch to `GetScreenGeometry` to report physical size of display. See if it helps.

https://github.com/beyond-all-reason/spring/commit/98b14cea56cf380c8abc70c74c9574695a4ea277

**Comment by WatchTheFort** [comment]
Shouldn't ii support alt-tab, as it is a borderless window?

**Comment by lhog** [comment]
There's a bit of overlap between II and IV. Technically they are made differently and have that `GetScreenGeometry` behavioral difference, but overall they should feel similar.

Does number II resist alt-tabbing?

**Comment by WatchTheFort** [comment]
It shouldn't, and currently it doesn't

**Comment by GoogleFrog** [comment]
I don't see any reason a user would want windows to resist alt-tabbing. If there is a technical limitation it make sense, but I wouldn't want alt-tab resistance added on top of anything.

I want display mode II, and I want it to not resist alt-tab, but as far as I know it cannot be brought about by Spring.SetConfigInt. It currently sanitises itself to exlude the taskbar. Maybe add a springsetting for ignoring or including the taskbar in such sanitisation? Ie, this didn't help:

> But I can understand the need to have physical size in Spring.GetScreenGeometry() so I'm adding 98b14ce default on switch to GetScreenGeometry to report physical size of display. See if it helps.

It reports the full screen but doesn't let me set it as a resolution.

As far as I can tell this _must_ be done via springsettings and Spring.SetConfigInt. I don't think additional callouts for finer control are useful as I want the window to display correctly when the player launches spring. So it has to be supported by springsettings.

**Comment by lhog** [comment]
> I don't see any reason a user would want windows to resist alt-tabbing. If there is a technical limitation it make sense, but I wouldn't want alt-tab resistance added on top of anything.

It's just the way system works, it's not coded by me and it has always been the case. There are two modes of fullscreen:
`SDL_WINDOW_FULLSCREEN` (I. in my list above) is exclusive one, system is **expected** to block your alt-tab attempts `SDL_WINDOW_FULLSCREEN_DESKTOP` (II. in my list above) on the other hand is expected to take full (physical) screen and not fight with user for exclusivity. See:
https://stackoverflow.com/questions/50893271/whats-the-difference-between-sdl-window-fullscreen-and-sdl-window-fullscreen-de

> I want display mode II, and I want it to not resist alt-tab, but as far as I know it cannot be brought about by Spring.SetConfigInt. It currently sanitises itself to exlude the taskbar. Maybe add a springsetting for ignoring or including the taskbar in such sanitisation? Ie, this didn't help:

First of all the current system is fully `Spring.SetConfigInt` configurable. There's simply no other way to configure windows. Even `Spring.SetWindowGeometry` I mentioned, uses the same basic configuration variables as you do from a widget. No magic here.
What you want for number 2 (borderless, fullscreen) is the following:
```
Fullscreen = 1
WindowBorderless = 1
WindowPosX = 0
WindowPosY = 0
XResolution = <displayX>
YResolution = <displayY>
```
this however is only true for the main display. Since it's hard to find right `WindowPosX/WindowPosY/XResolution/YResolution` for arbitrary display number the following helper has been created:
https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Lua/LuaUnsyncedCtrl.cpp#L3324-L3339
which in turn calls
https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Rendering/GlobalRendering.cpp#L1074-L1105
that does nothing outstanding as you can see.

**Comment by lhog** [comment]
UPD: I misled you with I. and II. types. See updated posts
