### ISSUE TITLE
105.1.1-941-g941148f Recent marker indicator is black

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#285]
![image](https://user-images.githubusercontent.com/1318249/170824020-51a98de2-698c-433c-ad97-344fb4fd26bc.png)

Look closely in the red box for some faint black lines. These are rotated squares that scale in and out on the minimap to indicate that a marker has just been placed. The lines should be white, and they were white on 104+.

This is with luaui disabled.

Happens in 841 too.

**Comment by Beherith** [comment]
This is caused by my change on binding unbinding the LuaTexture $specular
For the record, I dont even know what $specular contains, or its format, it is only used in a single widget in any game, and even there, it hardly has any effect, should be superceded by using newer things. 

For the record, this bug was introduced in https://github.com/beyond-all-reason/spring/commit/ff68bed5ccd7eae43a620874d82a436bbf944fd9

Related to : https://github.com/beyond-all-reason/spring/issues/286
#286 
Current suggested resolution is deprecation of $specular.

**Comment by GoogleFrog** [comment]
This bug happens in 841, released around Janurary 2022, and with lua disabled. It isn't resolved by not binding $specular.
