### ISSUE TITLE
Airmesh assetion failure on Ravaged_v2

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#33]
`assert(smoothed[x + y * lineSize] <= std::max(readMap->GetCurrMaxHeight(), 0.0f));`

**Comment by marcushutchings** [comment]
Investigated. The blur function goes over the max height by a tiny fraction due to inaccuracies of floating point numbers. The assertion is too strict. I have relaxed it a little so that it can be used to catch real problems rather than rounding issues. This fix will go out as part of https://github.com/beyond-all-reason/spring/issues/28

```
Blur reached: 344.993988
ReadMap Max: 344.993652
```

Closing issue.
