### ISSUE TITLE
Kerning size is too big sometimes

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#345]
https://www.youtube.com/watch?v=zqwz945Lc1I&ab_channel=AKU

![image](https://user-images.githubusercontent.com/1476261/186272398-1c518b0f-3c2c-4c4d-b06b-ba326ca3119f.png)
![image](https://user-images.githubusercontent.com/1476261/186272432-d6014d65-fa6b-40a9-aa63-b5e8a48f6c00.png)

TODO: Make a build with font substitution logging in hope to get the broken font file.

**Comment by WatchTheFort** [comment]
I think that in the end, we're going to want to supply all font files ourselves, and do all font substitution in-house, rather than relying on the OS font substitution.
The reason is that we cannot control what OS font substitution will look like, and we want complete control over the appearance of the game.

**Comment by icexuick** [comment]
agree with WTF

**Comment by lhog** [comment]
Closing as DUP to https://github.com/beyond-all-reason/spring/issues/381
