### ISSUE TITLE
Exit-only yardmap types

### ISSUE THREAD

**Issue by WatchTheFort** [beyond-all-reason/spring#453]
### Problem
The construction area of a factory is yardmap types `c` or `i` or `y`, which are treated the same as open land.

This results in units able to enter factories, either due to pathing or move orders, and blocking the factory from further construction. This is particularly a problem for AIs.

It also results in the problem of being able to build additional structures inside the factory's open yardmap area.

### Solution
Change these yardmap types to be exit-only.

They would be open to any unit inside it, but blocking to any unit outside. This would allow units to still leave the factory themselves, while blocking other units from entering it, as well as not allowing other construction inside.

As a bonus, this would also allow the ability to place exit pads in front of factories, preventing the possibility of accidentally blocking the exit to a factory with other buildings.

https://github.com/beyond-all-reason/Beyond-All-Reason/issues/612

**Comment by WatchTheFort** [comment]
Comments from @sprunk from Discord:

1.  check that this doesn't break any assumptions about pathing always being 2-way. all pathing becoming more costly to accomodate this would suck
2. you might still need a gadget polling the buildpad in case wreckage ends up clogging it (since it won't leave on its own)
3. only the pathing part of yardmap is needed, engine support for making areas unbuildable yet pathable exists (buildmask)

**Comment by sprunk** [comment]
> Change these yardmap types to be exit-only.

Don't touch the old ones, add new ones with this behaviour.

**Comment by sprunk** [comment]
If the engine-side fix is expensive you can also solve the problem gameside. Instead of upheaving the whole pathing system you can just poll factories and forcefully push units out if they're stuck inside, which you will still need anyway for wreckage and/or edge cases (like stunned units, or very dense clogging) since these won't necessarily path out on their own.

**Comment by WatchTheFort** [comment]
But that won't stop units from pathing into the factory. What stops an infinite loop of the factory teleporting a unit outside and the unit wandering right back in?

**Comment by sprunk** [comment]
Pushing back the blocker unblocks construction, at which point a new buildee appears, which fulfills the goal of the system and also prevents reentry.

**Comment by WatchTheFort** [comment]
Just saw in a stream an enemy unit attacking a factory within the open yardmap area, causing friendly units to refuse to shoot the enemy, due to avoiding friendly fire on the factory.

**Comment by marcushutchings** [comment]
Link and timestamp, or screenshot please.

**Comment by WatchTheFort** [comment]
@marcushutchings https://www.twitch.tv/videos/1713357933?t=00h27m11s

**Comment by marcushutchings** [comment]
So they weren't trying to use ground units to kill the enemy unit.

**Comment by WatchTheFort** [comment]
No, it was gunships

**Comment by sprunk** [comment]
It doesn't generally matter what unit they were trying to use to kill it, it might as well have been turrets - the problem here is that the chicken's hit-volume got inside the factory's hit-volume (in this case by pathing).

The two-sided factory opens up some questions though, if you were to tackle it via engine paths after all. Which of the following paths should be legal for a unit to take (black is unpathable, grey is exit-only, white is pathable, colors are various units)? Note that a factory yard is larger than a single pathing square so an exit-only tile must still allow entry from other exit-only tiles, letting units loiter around and keep blocking the fac. Note that easy solutions like "only allow entry if distance to closest normal tile does not decrease" are not only going to cost even more due to being stateful but also ruin some gameplay considerations. In particular, the green path is supposed to be takeable (the unit might have to path north because that might be its initial facing, but is supposed to be able to exit south because that is why the other exit exists).
![image](https://user-images.githubusercontent.com/2573076/213888260-15c0b157-8707-42f9-8f4b-9270555480af.png)

**Comment by marcushutchings** [comment]
As far as I'm concerned you can move from exit-only to exit-only fine. You can't move from open to exit-only. For optimal routing, let the pathing system do it.

**Comment by sprunk** [comment]
The example is not about routing per se, it doesn't matter whether those routes were ordered by a player explicitly or as a result of the pathfinder. It's about fulfilling the original reason for this request - if the unit can move around the exit-only area freely and the new feature boils down to "cant enter the area", then you will still need something to compel it to exit. For allied units this is usually bugger-off. For enemy units (for example pushed onto the exit-only area via impulse) and features (for example because a freshly created unit died) this would not help.

**Comment by GoogleFrog** [comment]
I solved most of this 15 years ago. https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_prevent_lab_hax.lua

Solve the rest with good factory geometry design.

The feature request is fine, but not vital.

**Comment by marcushutchings** [comment]
We may be able to solve this with QTPFS. Units are allowed to path out of blocked area if they are starting in it. I can probably achieve that with a new Yardmap block type.

**Comment by sprunk** [comment]
Is QTPFS going to make wrecks path out of a factory?

**Comment by sprunk** [comment]
Good. More questions:
1) is QTPFS going to _force_ (i.e. not just _allow_) units to move away from a blocked area? I don't want things like grounded ships zipping across the map to the nearest sea, or tanks sliding through rough mountains towards a plain. On the other hand if this is voluntary, how is it going to solve enemies that just get a Stop command and won't want to move?
2) what else would be convenient to do if you already need to have a gadget that polls factory areas and kicks features out?

**Comment by marcushutchings** [comment]
Is it not possible to have factories auto-reclaim a wreck that's in the way of a build order?

**Comment by marcushutchings** [comment]
I was thinking about how to support bridges in Recoil via QTPFS, which would be to create a navmesh over a feature and link it to the quad-tree nodes. Now this idea could, in theory, be extended to create a NavMesh that connects one-way to quad-tree - i.e. units inside the factory can get out and units outside the factory can't path in. Once you've setup the mesh and linked it, there's no special cost or impact on the pathing system. This wouldn't be possible with HA*.

**Comment by sprunk** [comment]
> Is it not possible to have factories auto-reclaim a wreck that's in the way of a build order?

Sure, the gadget will look largely the same except with `SetFeatureResources` instead of `SetFeaturePosition`.

> connects one-way to quad-tree (...) no special cost or impact on the pathing system

Sounds good as a general engine feature (even though it doesn't solve the blocked factory issue at hand).

> bridges

Sounds good, it's a common feature request. Though keep in mind that this may break a ton of assumptions, mostly related to a deformable map.

For example:
* (A) what happens if terrain gets deformed such that the bottom gets a spike that "pierces" the bridge, do units follow the local  navmesh node and just ghost through the spike, or can they be made to obey it even though it's not actually an adjacent node on the quadtree? Worse, you could have multiple intersecting bridges (nav meshes).
 * (B) what happens if terrain gets deformed at the edge? Does a game need to monitor or prevent this, or does the engine handle it for free?
 * (C) what happens if a unit is too tall to path under a bridge? This has to exist to some extent already (units pathing on the seafloor vs buildings floating on the surface) but perhaps arbitrary bridges present more challenges.
 * (D) what about units thrown via impulse, or other things that deal with ground (for example projectiles - these treat units and terrain differently, is bridge a form of terrain)?
![image](https://user-images.githubusercontent.com/2573076/225974216-d40350e9-af9d-43b8-b0cc-0d03d357325b.png)

**Comment by marcushutchings** [comment]
> Good. More questions (because I'm an asshole):
> 
>     1. is QTPFS going to _force_ (i.e. not just _allow_) units to move away from a blocked area? I don't want things like grounded ships zipping across the map to the nearest sea, or tanks dropped from a shot-down transport sliding through rough mountains towards a plain. On the other hand if this is voluntary, how is it going to solve enemies that went inside a factory that just get a Stop command and won't want to move?
> 
>     2. what else would be convenient to do if you already need to have a gadget that polls factory areas and kicks features out?
> 
>     3. has anything useful and largely stealable been linked in the handful of posts above, that would let us avoid tacking on overhead to the core system that is pathfinding?

1. No, it just won't give the unit

**Comment by marcushutchings** [comment]
Sorry, misclicking buttons....

**Comment by sprunk** [comment]
> 1. No, it just won't give the unit

Why won't the unit just stay in
What is there to force the unit to
If the controller of the blocking unit presses Stop, the unit will
Not a robust way to

**Comment by marcushutchings** [comment]
I've had another look at this and I have what looks to be a viable approach. As I'm working on this it has occurred to me that rather than add a new yardmap type, it may make more sense to improve the behaviour of the construction yardmap type, 'c'. I wanted everyone's thoughts on this.

So the new exit-only behaviour is as thus:

1. Units outside the exit-only area cannot enter.
_1.a (units inside the exit-only area are free to move around as normal)_
2. Buildings cannot be built inside or overlapping an exit-only area.

So, rather than have a factory alternate between 'open' and 'closed' yardmap states - it just stays as an exit-only because there is no longer a need to change the ground blocking map.

Note: the state machine behaviour of factories will not be touched - only the switching of the ground collision map. I can imagine factories open and closing animations are still desired.

This has the benefits of:
1. Enemy/friendly-ai units can't jam themselves inside your factories and effectively shut them down
2. Enemy/friendly-ai units can't build stuff inside your factories and effectively shut them down
3. The map damage events are not needed when the factory switches state, saving on performance

**Comment by sprunk** [comment]
How do you implement a gate with the change? Think sc2 supply depot

**Comment by marcushutchings** [comment]
That's a fine point. Glad I asked.

**Comment by sprunk** [comment]
Adding a new letter with the new behaviour and keeping `c` as-is sounds fine.

**Comment by WatchTheFort** [comment]
Does any game depend on the current behaviour, i.e. units being able to drive in to and block a factory and buildings can be built in an open factory?

**Comment by marcushutchings** [comment]
I think Sprung was suggesting that you can use the current behaviour to create gates rather than necessarily use it for a factory. I guess you can turn a unit's collision on and off to achieve something similar, but that applies to the whole unit rather than part of a unit - with the yardmap, you could keep walls either side. Not sure if anyone does that though.

**Comment by WatchTheFort** [comment]
But you can't...

1. Gate opens
2. Build structure inside open footprint
3. Gate now blocked

**Comment by marcushutchings** [comment]
I could make it so that when yardmap 'c' is open, it also blocks building structures, but without the impact on unit pathing.

**Comment by TheSilverHornet** [comment]
If it doesn't prevent pathing, we'd still have the issues with units clipping into shipyards

**Comment by TheSilverHornet** [comment]
Roger, apparently I missed that - it sounds likely to be ideal then

**Comment by sprunk** [comment]
> Does any game depend on the current behaviour

Yes, any game with gates does.

> Build structure inside open footprint

Today's homework reading assignment:
* building masks
* `gadget:AllowUnitCreation`

> I could make it so that when yardmap 'c' is open, it also blocks building structures, but without the impact on unit pathing

`c` blocking buildings by default sounds good but I believe it would become a superset of #1303 (it's 1303 with added toggleability) and that one was apparently hard. If you manage to do it, great, but no big deal either way because we still have masks and gadgets.

**Comment by GoogleFrog** [comment]
> Does any game depend on the current behaviour, i.e. units being able to drive in to and block a factory and buildings can be built in an open factory?

There are a few ZK factories that look like units should be able to drive through them when open, and units can drive through them, and we don't have any issues with it. So yes, ZK depends on it to the extent that the way things look and the way things behave should agree.

> I could make it so that when yardmap 'c' is open, it also blocks building structures, but without the impact on unit pathing.

Personally I would like yardmap to be irrelevant to structure placement. Ie, you just can't place structures so that they overlap, regardless of the yardmap. But I have already implemented that in ZK via a gadget, and removing overlap via lua is much harder than adding the ability back in, so speaking more objectively, I wouldn't want a forced behaviour change within the engine. So a toggle to let structures not care about yardmap for placement would be good, or at least convenient.

> Today's homework reading assignment:

Can you try implementing the building mask version in ZK? The UI is a bit bad currently because we just use AllowUnitCreation and AllowCommand, so the placement UI does not reflect structure blocking. I recall looking into building masks and them being LOS hax.

**Comment by sprunk** [comment]
> I recall looking into building masks and them being LOS hax.

Still the case #779

**Comment by marcushutchings** [comment]
> Personally I would like yardmap to be irrelevant to structure placement. Ie, you just can't place structures so that they overlap, regardless of the yardmap. 

I had a plan a while ago to add `YARDMAP_WALKABLE   // open for walk    (    walkable, not buildable)`, I can now make that happen: so instead of using 'y' for open, you'll be able to use 'w' for walkable only.

**Comment by lostsquirrel1** [comment]
Before I try merging https://github.com/beyond-all-reason/spring/pull/1464. I wanted to check whether we had game-side solutions for all of these issues.

So, can game side reliably
1. prevent mobile units from blocking a factory build area.
2. prevent a building being built in a factory build area.
3. prevent a unit from getting inside the collision volume of a factory and avoid being targetable by defending units.
4. prevent a building from being built and blocking an open gate.

and anything else I forgot to ask?

**Comment by sprunk** [comment]
Exit-only yardmap tiles don't even fully solve those:
* 1\) an enemy mobile unit can still enter an exit-only area if pathing isn't involved (e.g. pushed inside via impulse from a Pounder), and it can stay there indefinitely since nothing compels it to actually leave.
* 5\) blocking features can still enter an exit-only area (unit from the above example dies; or, unit going in the direction of the exit dies before the exit-only area, wreck keeps momentum and slides there; or, a unit that was never subject to the tile, e.g. aircraft, places itself above and its wreck falls down).

https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_prevent_lab_hax.lua steal, solves 1-5 (135 by just pushing stuff out, and 24 by `AllowUnitCreate`).
