### ISSUE TITLE
Water looks different in 841 and 1393

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#564]
The water is worse on FolsomDamDeluxeV4 in 1393. It is worse in the sense that it doesn't match my requirements, which involve being able to see amphibious units underneath it.

This wouldn't be such a problem if my real issue was resolved, which is that Spring.SetWaterParams seems to do nothing. It at least does nothing while the game is running, and for the old parameter list I have. It does nothing in both 841 and 1393. I am testing with the ZK menu path that tweaks individual parameters in a pretty direct way.
![image](https://user-images.githubusercontent.com/1318249/210379028-71f5a2da-ab8b-4105-9234-08f37029711b.png)

My previous experience with this widget says that screwing around with repeatX should result in a pretty obvious change to the water. This is all with water 4.

841:
![image](https://user-images.githubusercontent.com/1318249/210378054-e7d335b2-fed8-40d1-bf20-c66b28cd032a.png)

1393:
![image](https://user-images.githubusercontent.com/1318249/210378163-b2bf845e-b401-4a58-a4bc-82e3b79194db.png)

**Comment by Beherith** [comment]
Works for me in 1429

![image](https://user-images.githubusercontent.com/109391/210380653-51dae6f2-a663-4f50-95aa-ee6bd82c90d4.png)

**Comment by lhog** [comment]
`repeatX` and `repeatY` are only relevant for Basic water.

**Comment by sprunk** [comment]
I think the point was that
1) something changed with various params between 841 and current, because the screenshot looks different.
2) something changed with `repeatX` and possibly other params before 841, because it used to do something.

**Comment by GoogleFrog** [comment]
> `repeatX` and `repeatY` are only relevant for Basic water.
> 
> Even in 841:

1. I fiddled with all the other settings and they also did nothing.
2. The settings don't do anything in 841 as well.
3. My memory says otherwise from when I implemented the widget.

**Comment by GoogleFrog** [comment]
Spring.SetWaterParams works in 104-1681
![image](https://user-images.githubusercontent.com/1318249/210463378-dc2a6bb6-14b9-461d-bfae-3cf265c5978e.png)

**Comment by GoogleFrog** [comment]
Works in 475
![image](https://user-images.githubusercontent.com/1318249/210463604-b5d26a5c-c4cb-4a3c-8ea7-37f4c93288fb.png)

**Comment by GoogleFrog** [comment]
Hmm scrap all that. The bug seems to be intermittent. I had it working in 841 with no code change. It still doesn't work in 1393 though.

**Comment by lhog** [comment]
Good, so:

1) regarding the different look it's fixed in https://github.com/beyond-all-reason/spring/commit/47a688dbff32efcd8cbb0318f1af0e9c8a5ece4d
2) 841 and alike reacting to `repeatX` is some kind of side effect, because the water code used to be slightly insane. Changing `repeatX` was never meant to do anything for BumpWater as you can see it's not mentioned anywhere in https://github.com/beyond-all-reason/spring/blob/spring_bar_%7BBAR105%7D105.1.1-841-g099e9d0/rts/Rendering/Env/BumpWater.cpp Consider the old behavior a bug.
3) The rest of the controls, applicable to BumpWater, work for me just fine (I use the same widget you use in ZK). At least in the latest `105.1.1-1450-g15f3d80062` (current HEAD)

**Comment by lhog** [comment]
With the BumpWater look fixed to be like in 841, and Lua controls reportedly working (no changes were made), I assume there's nothing left to do here.
