### ISSUE TITLE
Coil is a much worse than than Recoil

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#584]
The name seems to be in the process of sticking so we had better change it to Recoil before it is too late. Recoil has a better number of sylables, better shortening, sounds vaguely military, and even implies doing something to a spring rather than just being a spring. There was a chat on discord about this near the end of the rename thread.

**Comment by lhog** [comment]
The springrts vs spring.io history would repeat itself with https://github.com/facebookexperimental/Recoil

**Comment by Krogoth100** [comment]
Here are my 2 cents, because I missed out on all this rename stuff completely when it took place.
If to choose between Coil and Recoil, I would choose Coil.
But I am a big fan of the "Spring" name. Because this name bears many meanings; there aren't much names like this one. It is a season, it is also a water, it is also a jump, and many other things. If you make a logo for it, you could use any of this. It's an excellent name overall.
If it were up to me, I would use "Spring: Coil" together, but not only because of the above, it is also an engine with quite a history. It would not be fair to make a supposedly excellent modern engine out of it and then just drop its original name, as if it transformed into something else. The right decision should be bigger than an internal conflict.

**Comment by lhog** [comment]
Spring is unfortunately unavailable due to irrational stubbornness of of their maintainer.
Recoil will gradually become the new name.
