### ISSUE TITLE
1667 Reclaim highlight shader is offset

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#721]
- Spawn a factorycloak_dead.
- Select a constructor.

![image](https://user-images.githubusercontent.com/1318249/227696551-46118176-b756-415c-884c-95661e05fc3f.png)

The highlight is drawn by a recent GL4 widget https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gfx_highlight_api_gl4.lua

The offset is sort of random.
![image](https://user-images.githubusercontent.com/1318249/227696709-b6faf87e-9f3e-41bd-b624-15e831365258.png)

**Comment by lhog** [comment]
1667 has a breaking change, related to the implementation of skinning. That caused the need to change of basic model vertex format. Gameside this requires updates to GL4 widgets/gadgets using calls `vbo:ModelsVBO()` in Lua code.
Since ZK will likely want to jump back and forth between 1544 and newer engines it's advisable to add something like a runtime switch controlling the vertex format. Example is here https://github.com/beyond-all-reason/Beyond-All-Reason/commit/cc414edd20af3dc488d03598468905fbaa344c1a
Unless you plan to employ skinning it's enough to replace:
```
layout (location = 5) in uint pieceIndex;
````
with
```
layout (location = 5) in uvec2 bonesInfo; //boneIDs, boneWeights
#define pieceIndex (bonesInfo.x & 0x000000FFu)
```
In the vertex shaders.

I will document the skinning part and migration properly when I have a spare minute
