### ISSUE TITLE
KeyChainTimeout in springsettings.cfg being ignored on game load

### ISSUE THREAD

**Issue by resopmok** [beyond-all-reason/spring#831]
When a game loads, the `KeyChainTimeout` setting is not being read or something, it always loads the engine default of 750 instead of the value set there. For example, if `KeyChainTimeout = 250` is in springsettings.cfg, on a new load of the game, it will operate at 750ms instead of 250ms, even though the infolog shows the 250 value being loaded. Using `/set KeyChainTimeout 251` will then allow you to operate at 251ms, the new value is written to springsettings.cfg, but on next load it will again operate at 750ms.
LSR confirmed this behavior in testing using a timeout tester, I did it by using sixteenth and triplet rhythms based on a 60bpm beat.
LSR will comment on this thread with more information.
@badosu

**Comment by lolsteamroller** [comment]
The engine's default is always 750, see 
https://github.com/beyond-all-reason/spring/blob/441af871b4fd3f4c8bbba257890e36b1cc92aae3/rts/Game/UI/KeyBindings.cpp#LL263C16-L263C16

The config handler does read and update the value, if it is changed configHandler->NotifyOnChange(this, {"KeyChainTimeout"});, but doesn't load the existing value from springsettings.cfg

In https://github.com/beyond-all-reason/Beyond-All-Reason/blob/cba8a4331aa12f6b8cfb190ee6fde1ddff49d48e/luaintro/springconfig.lua#L161

If the value is default at the start -> it will be adjusted to be 333 https://github.com/beyond-all-reason/Beyond-All-Reason/blob/cba8a4331aa12f6b8cfb190ee6fde1ddff49d48e/luaintro/springconfig.lua#L161

but after exiting the game, this value will be saved as 333, hence on the next loading the springconfig won't set the value to 333, resulting in engine default 750 (since the engine only reads updates to the value, but doesn't read the config itself directly.)

---

Testing process: (only use config, use low value, impossible to chain).

Widget reads value from config, but it is still chaining.
![image](https://github.com/beyond-all-reason/spring/assets/7465747/2db27304-fd1a-47aa-ae4b-0ab28e0aeab7)

After using `/set KeyChainTimeout 250` directly in the same game.

Widget value is updated, and there is no chain (the macro didn't change)

![image](https://github.com/beyond-all-reason/spring/assets/7465747/fdc01e33-ceb5-443c-aa90-28ec77e5a9e9)

Update macro in the same game and it chains as expected.

![image](https://github.com/beyond-all-reason/spring/assets/7465747/d44b2153-bd33-4a8d-8092-0c3afa0a3fe3)


Wipe all values in config start new game:  Widget loads value as 333 due to springconfig and it works as 333 

![image](https://github.com/beyond-all-reason/spring/assets/7465747/45573976-1d15-4660-ba0a-9b42ca12f14e)

Exit the game, start new game, widget shows 333, but the real value is 750 from the macro (it chains when it shouldn't )

![image](https://github.com/beyond-all-reason/spring/assets/7465747/aa4d9ce4-6778-4ea6-86bc-0c56935ec0fa)

**Comment by lolsteamroller** [comment]
@sprunk I'm curious, maybe you can tell me, is it engine's or games responsibility to load this value in this case? Engine does save the value back to springsettings.cfg, so it might be easy fix on the lua loading side.

**Comment by lolsteamroller** [comment]
Made PR on BAR side here: https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1821
Will mark this as resolved, if it supposed to be done at the game side, or when we test and it works.

**Comment by badosu** [comment]
Responsibility to load is from engine, should be a quick fix. I'll get to it when possible
