### ISSUE TITLE
font substitution is not working for windows

### ISSUE THREAD

**Issue by Anarchid** [beyond-all-reason/spring#87]
Spring natively supports unicode, but this only really works if you have the characters for non-latin languges eg chinese/korean/japanese.

Most fonts do not have these characters because there are so many of them, so text rendering usually does font substitution - asked to render a character which selected font does not have, it picks a glyph from a font that does have it.

This is by default not working in Spring *on Windows*, presumably because it requires a fontconfig cache. Generating this cache on WIndows is supposed to occur by invoking Spring witht the `--gen-fontconfig` CLI parameter, but it seems to  somehow fail:

![image](https://user-images.githubusercontent.com/3822768/135850572-10b924e7-6137-4851-b473-0a9865709cc1.png)

![image](https://user-images.githubusercontent.com/3822768/135850639-7f0fd26e-1f46-428c-b980-72a578d8a91d.png)

Comments on https://github.com/spring/spring/commit/2225f0f1cf68870167bd606666a61d01c11b4f09 suggest that parts of that commit may be noop but i have no idea if that's relevant.

**Comment by WatchTheFort** [comment]
This will be very helpful for I18N support of Asian languages

**Comment by WatchTheFort** [comment]
Even when this is fixed, will this only support native OS font substitution, or will we be able to specify a fallback font, or series of fallback fonts, Spring should use?

**Comment by lhog** [comment]
I expect it doesn't work because of outdated mingw libs. In particular mingw version seems to ignore Windows/Fonts dir, despite fonts cache is aware of it. 
I've got substitution working perfectly with MSVC build, that has libs ~upstream level of freshness.

Also I'm not sure it was a wise decision to demote font caching to a separate spring switch. How many people will actually run it? 1 out of 100? Perhaps a few more if they are told to do so.

But first things first : need to update fontconfig and freetype libs for MinGW.
Next probably revert the commit disabling fontconfigs for the main spring run.

**Comment by WatchTheFort** [comment]
The players would not run Spring with a switch, rather the fallback fonts would be included with the game, and the game would tell Spring which font(s) to use as fallback when a glyph is missing. The fallback logic would have to be included in Spring, otherwise the game would have to install the fonts on the player's system, and I'm not sure whether an application can tell the OS which fallback font to use.

One possible alternative is to transplant the Asian character planes from the Asian font into the desired BAR font, so that Asian characters still render, but numbers/Latin/Cyrillic/etc. characters still appear as we intend.

**Comment by Anarchid** [comment]
> Also I'm not sure it was a wise decision to demote font caching to a separate spring switch. How many people will actually run it? 1 out of 100? Perhaps a few more if they are told to do so.

ZK look at this issue assumes that it would be lobby doing this automatically whenever the user switches to a language that requires fontsub, eg Chinese for which we have a complete translation that we cannot deploy for windows.

> The fallback logic would have to be included in Spring

This is one of the core purposes of the fontconfig library. Which is already in Spring.

**Comment by lhog** [comment]
Guys, if someone wants to aid, please compile recent releases of FontConfig and FreeType under mingw with all 3rd party libs either disabled and/or better statically linked into dlls. Similarly how current dlls are done:

https://github.com/beyond-all-reason/mingwlibs64/blob/master/dll/libfontconfig-1.dll
https://github.com/beyond-all-reason/mingwlibs64/blob/master/dll/libfreetype-6.dll

I will also need .lib files and include sources.

**Comment by lhog** [comment]
Ok, since no one has done the requested item so far, I've replaced mingw dlls with msvc ones. The result looks good:

![screen02203](https://user-images.githubusercontent.com/1476261/150003011-7bddabd9-7ebb-49b6-ab34-9191082933ce.png)

So items to take care of are the following:
* Fix build issue https://github.com/beyond-all-reason/spring/actions/runs/1714445864
* Merge some of the https://github.com/beyond-all-reason/spring/commit/474842e72fecc9085ff9dd187f592a94816f1e83
* Probably revert https://github.com/spring/spring/commit/2225f0f1cf68870167bd606666a61d01c11b4f09
* Ideally replace vclibs64 dlls with properly built mingw64 ones

**Comment by WatchTheFort** [comment]
Are we able to specify and supply the fallback fonts, or do we rely on whatever the OS decides to provide?

**Comment by lhog** [comment]
[FontConfig ](https://www.freedesktop.org/wiki/Software/fontconfig/) decides that.
On Linux it can be configured via a set of convoluted xml files. How to provide a config for it on Windows is a million dollar question, but to be honest only one person out 10000 would do that on Windows. So it uses some default configuration.

The matching itself is outlined here:
https://github.com/beyond-all-reason/spring/blob/BAR105-FC/rts/Rendering/Fonts/CFontTexture.cpp#L295-L331

As you can see a lot of things are requested to be matched, so substitution should generally be good.

**Comment by lhog** [comment]
Another chance to accomplish a community task:

Related to https://github.com/beyond-all-reason/spring/commit/16124a2dfa334d442d0d149d9ef7c64a1a823b79
The cache build process itself is offloaded to a thread, but the main thread should show draw something smart while user for task to accomplish. This "something" cannot contain fonts, nor can show any progress bar (because FC cache build progress is not trackable). Ideas / code are welcome.

**Comment by WatchTheFort** [comment]
Is this something that only has to be run once at install, run every time Spring starts, or something in between?

**Comment by lhog** [comment]
Ideally it is run once a lifetime, maybe one per engine lifetime (unsure). Adding new fonts to fonts or system dir can cause recaching.

In general it should be mild, but there was a reason original commit exists, so apparently on some systems building font cache used to take ~1min

**Comment by WatchTheFort** [comment]
Then it should be done on initial download & install, when there is an expectation from the user that the process will take longer, rather than when starting the game, when there is an expectation that it will be quick.

**Comment by lhog** [comment]
LOL:
![image](https://user-images.githubusercontent.com/1476261/150204027-03063884-8e06-48e9-b0da-32b5b0d18f8d.png)

> Then it should be done on initial download & install.

It's still possible, but since no guaranteed, the first start will be building cache in case it was not built earlier.

**Comment by WatchTheFort** [comment]
We're allowed to cheat. Have the install script spawn Spring headless and build all the caches as part of the install process.

**Comment by Anarchid** [comment]
> The cache build process itself is offloaded to a thread, but the main thread should show draw something smart while user for task to accomplish. This "something" cannot contain fonts, nor can show any progress bar (because FC cache build progress is not trackable). Ideas / code are welcome.

You can use it as part of general load fake progress bar, similar to what ZK does. E.g. fonts cache not yet built -> freeze progress at 55%

**Comment by lhog** [comment]
> You can use it as part of general load fake progress bar, similar to what ZK does. E.g. fonts cache not yet built -> freeze progress at 55%

That is apparently much more difficult than I thought.
1) The font caching happens before the engine gains the ability to render fonts 
2) VFS is not initialized yet, so standard shaders cannot be used as well.

For now I leveraged SDL renderer to display a primitive BMP (see an exemplar of beauty above). That's the best I can figure out without tedious stuff like embedding shaders into spring as `const char*` text.

Feel free to extend it with https://wiki.libsdl.org/CategoryRender, I'll accept PRs.

**Comment by Anarchid** [comment]
Oooh. Does this need any buttons to be pressed to end up accessible user-side? I'm going to try doing the commander skins thing this weekend, so could also get someone to test the fonts thing.

**Comment by lhog** [comment]
Was going to make a build, but MSVC dlls broke one of the scripts and my attempt to fix it was only looking good, in fact it is producing invalid files.

Will take some (short) time to fix.

**Comment by lhog** [comment]
https://github.com/beyond-all-reason/spring/releases/tag/spring_bar_%7BBAR105%7D105.1.1-791-g4403780

![image](https://user-images.githubusercontent.com/1476261/150289741-fa5b4a78-1b42-4da1-bc87-9ad336efb5d4.png)
