### ISSUE TITLE
Weird model warning

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#922]
Warning about null in local model piece constructor. Maybe related to model desyncs?
```
In constructor 'LocalModelPiece::LocalModelPiece(const S3DModelPiece*)',
    inlined from 'static void LocalModelPiece::_ConstructInstance(void*)' at /spring/rts/Rendering/Models/3DModel.cpp:21:1:
/spring/rts/Rendering/Models/3DModel.cpp:433:32: warning: 'this' pointer is null [-Wnonnull]
  433 |         dir = piece->GetEmitDir();
      |               ~~~~~~~~~~~~~~~~~^~
```
Earlier in line 21 there's
```cpp
CR_BIND(LocalModelPiece, (nullptr))
```
and `CR_BIND` is a macro that expands to running the constructor with `nullptr` piece as argument. But then the warning says this about the `this` pointer not `piece`, and also there's `assert(piece != nullptr)`. But then wouldn't that mean the `CR_BIND` is dead code, since if it ran it would have triggered the assert? Generally I am unsure what is going on there.

**Comment by lhog** [comment]
I've done some digging and I think this is most likely a linter brainfart.

A pseudo-constructor, defined by `CR_BIND(LocalModelPiece, (nullptr))` is never called indeed because `LocalModelPiece` instances are considered "embedded" objects. As far as I can tell such objects are created with `SerializeObjectInstance` and to quote the inline comments:
```
		/** Serialize an instance of an object, could be a structure embedded into another object
		 * The big difference with SerializeObjectPtr, is that the caller of this function
		 * controls the allocation of the object instead of the creg serializer itself
		 */
```
Long story short, the constructor is not called for "embedded" objects.

`piece` on the other hand is created right from the model pieces inside recursive `CreateLocalModelPieces()`. Pieces can be invalid runtime, but at least they're not nullptr, as they're allocated from a preallocated objects pool.

All in all, I don't think this warning is real.
